trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployADF
    displayName: 'Deploy Azure Data Factory'
    jobs:
      - deployment: DeployARMTemplate
        displayName: 'Deploy ADF ARM Template'
        environment: 'Production'  # This requires approval if configured
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  name: DeployADF
                  inputs:
                    azureSubscription: 'MyAzure'  # Replace with your Azure DevOps service connection name
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Debug: Show current working directory and list files
                      echo "Current directory: $(pwd)"
                      echo "Listing directory contents:"
                      ls -la

                      # Set variables using absolute paths for reliability
                      RESOURCE_GROUP="shanmuk_resource"
                      TEMPLATE_FILE="$(Build.SourcesDirectory)/template3.json"
                      PARAMETERS_FILE="$(Build.SourcesDirectory)/template.json"
                      DEPLOYMENT_NAME="adf-deployment"

                      # Deploy the ARM template
                      az deployment group create \
                        --name $DEPLOYMENT_NAME \
                        --resource-group $RESOURCE_GROUP \
                        --template-file $TEMPLATE_FILE \
                        --parameters @$PARAMETERS_FILE

                - task: PublishBuildArtifacts@1
                  inputs:
                    PathtoPublish: '$(Build.SourcesDirectory)'  # Publishing the repository content as an artifact
                    ArtifactName: 'ADFTemplate'